SELECT A.CODFILIAL, SUBSTRING(A.CODSECAO,13,3) AS UNIDADE, A.CHAPA, replace(A.NOME,'Ç','C') AS NOME, CONVERT(VARCHAR,A.DATAADMISSAO,103) AS ADMISSAO, 
CASE
	WHEN SUBSTRING(A.CODSECAO,13,3) = 'CRC' THEN CONVERT(VARCHAR,DATEADD(DAY,29,A.DATAADMISSAO),103) 
	WHEN SUBSTRING(A.CODSECAO,13,3) <> 'CRC' THEN CONVERT(VARCHAR,DATEADD(DAY,43,A.DATAADMISSAO),103) 
END AS AVAL45, 
CASE
	WHEN SUBSTRING(A.CODSECAO,13,3) = 'CRC' THEN CONVERT(VARCHAR,DATEADD(DAY,59,A.DATAADMISSAO),103) 
	WHEN SUBSTRING(A.CODSECAO,13,3) <> 'CRC' THEN CONVERT(VARCHAR,DATEADD(DAY,89,A.DATAADMISSAO),103) 
END AS AVAL90,
CASE
	WHEN SUBSTRING(A.CODSECAO,13,3) = 'JML' THEN 'PH JML - CASA DE PEDRA'
	WHEN SUBSTRING(A.CODSECAO,13,3) = 'OFC' THEN 'CLD'
	ELSE SUBSTRING(A.CODSECAO,13,3)
END AS ALMOX,
A.CODSECAO + ' - ' + B.DESCRICAO AS SECAO, A.CODFUNCAO + ' - ' + C.NOME AS FUNCAO, A.CODSECAO, A.CODFUNCAO, D.CPF, C.NOME AS DSCFUNC, B.DESCRICAO AS DSCSECAO, CONVERT(VARCHAR,DATEADD(DAY,43,D.DTNASCIMENTO),103) AS DTNASCIMENTO,
A.RECCREATEDON
FROM PFUNC A (NOLOCK)
INNER JOIN PSECAO B (NOLOCK) ON A.CODCOLIGADA = B.CODCOLIGADA AND A.CODSECAO = B.CODIGO
INNER JOIN PFUNCAO C (NOLOCK) ON A.CODCOLIGADA = C.CODCOLIGADA AND A.CODFUNCAO = C.CODIGO AND (C.NOME NOT LIKE '%APRENDIZ%' AND C.NOME NOT LIKE '%ESTAGIARIO%' AND C.NOME NOT LIKE '%ESTAGIÁRIO%')
INNER JOIN PPESSOA D (NOLOCK) ON A.CODPESSOA = D.CODIGO
WHERE A.CODCOLIGADA = 1
AND A.CODTIPO <> 'U'
AND A.REGATUAL = 1
AND A.MOTIVOTRANSFERENCIA IS NULL
AND A.RECCREATEDON > DATEADD(DAY,-1,GETDATE())
/*AND A.CHAPA IN ('011261','011325','010903','009059','003127','011397','011323','008852','008772','010818')*/
ORDER BY 2, A.DATAADMISSAO