-- SEMPRE VERIFIQUE O RM, ESTE CÓDIGO É APENAS PARA QUEBRAR GALHO

SELECT DISTINCT(C7_FILIAL+C7_NUM) FILIAL_PEDIDO, C7_FILIAL, C7_NUM, LTRIM(RTRIM(A2_CGC)) AS A2_CGC, A2_COD, A2_LOJA, LTRIM(RTRIM(A2_NOME)) AS A2_NOME, 
LTRIM(RTRIM(CTT_CUSTO)) AS CTT_CUSTO, LTRIM(RTRIM(CTT_CUSTO)) + ' - ' + LTRIM(RTRIM(CTT_DESC01)) AS CCUSTO,
C7_XCO, LTRIM(RTRIM(AK5_CODIGO)) + ' - ' + LTRIM(RTRIM(AK5_DESCRI)) AS CONTAORC, LTRIM(RTRIM(A2_BANCO)) AS A2_BANCO, LTRIM(RTRIM(A2_AGENCIA)) AS A2_AGENCIA, 
LTRIM(RTRIM(A2_NUMCON)) AS A2_NUMCON, C7_TOTAL, C7_EMISSAO, A2_DDD, A2_TEL, C7_COND, C7_PRODUTO, Z06_VENCTO, C7_DESCRI, A1_END, A1_MUN, A1_BAIRRO, A1_CGC
FROM SC7010 (NOLOCK)
LEFT JOIN Z06010 (NOLOCK) ON C7_FILIAL = Z06_FILIAL AND C7_NUM = Z06_NUM
INNER JOIN SA2010 (NOLOCK) ON C7_FORNECE = A2_COD AND C7_LOJA = A2_LOJA
LEFT JOIN CTT010 (NOLOCK) ON C7_CC = CTT_CUSTO
LEFT JOIN AK5010 (NOLOCK) ON C7_XCO = AK5_CODIGO
LEFT JOIN SA1010 (NOLOCK) ON C7_FILIAL = A1_FILTRF
WHERE SC7010.D_E_L_E_T_ = ''
AND Z06010.D_E_L_E_T_ = ''
AND SA2010.D_E_L_E_T_ = ''
AND C7_CONAPRO = 'L' 
/*AND C7_ENCER <> 'E'*/ 
AND C7_RESIDUO = ''
-- AND C7_FILIAL like '%' + :FILTRO1 + '%'
AND C7_NUM LIKE '%354015%'
ORDER BY C7_FILIAL, C7_NUM