select *
from VEXAMESPRONT
where codpessoa = 11135
 
 
select * from VEXAMESPRONTINFCLINICA 
where idconsulta = '111934'
and CODTABELA = 'INTAUDIO'
 
 
 
INSERT INTO VEXAMESPRONTINFCLINICA
(CODCOLIGADA,CODPESSOA,CODEXAME,DATAEXAME,CODTPINFCLINICA,VALNUMERICO,VALTEXTO,CODVALMEMO,CODCLIENTE,APLICACAO,CODTABELA,VALIMAGEM,IDCONSULTA,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)
VALUES 
(1,11135,'0281','2023-12-28 00:00:00.000','1000HZODVA',NULL,NULL,NULL,'0001','V')
 
 
SELECT * FROM GLINKSREL
WHERE MASTERTABLE = 'VEXAMESPRONTINFCLINICA'
 
 
SELECT * FROM GCONSIST
WHERE CODCOLIGADA = 1
AND CODTABELA = 'INTAUDIO'
 
 
SELECT * FROM GSISTEMA